services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10

  api:
    build: .
    container_name: fastapi_app
    restart: always
    environment:
      - DATABASE_URL=mysql+aiomysql://root:password@mysql:3306/myapp
      - JWT_SECRET=secret-key-for-development
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    command: uvicorn server:app --host 0.0.0.0 --port 4000 --reload

volumes:
  mysql_data:
