version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: myapp
    ports:
      - "27017:27017"
  api:
    build: .
    container_name: node-api
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
  init-admin:
    build: .
    command: ["node", "src/init-admin.js"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - mongodb
    restart: "no"
