name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_DATABASE: myapp
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")' --username root --password example --authenticationDatabase admin"
          --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MONGO_URI: mongodb://root:example@localhost:27017/myapp?authSource=admin
      JWT_SECRET: secret
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
